### PR TITLE
Make it compatible with newer kubernetes versions

### PR DESCRIPTION
**Pull request by 7fELF**
With kubernetes 1.20 I get errors like this one:

```
poster.go:72 Error retrying packet drop handling, backing off: packetDrop={LogTime:xx HostName:xxrcIP:xxDstIP:xx DstPort:xx Proto:TCP}, retryIn=selfLink was empty, can't make reference secs, error=1.919943941
```

I guess client-go used in kube-iptable-tailer is too old ([v8.0.0](https://github.com/kubernetes/client-go/releases/tag/v8.0.0) =Kubernetes v1.11.0)

I updated to the client go version v0.18.0 (=Kubernetes v1.18.0) and it solved the problem.

I had to switch the dependency management to go modules since this is what is used in the K8S project nowadays.

### CODE REVIEW

**Comment by 7fELF** [comment]
@dilyar85 Can you take a look so we can have k8s 1.20 compatibility upstream [please](https://media.giphy.com/media/V3TtZ4IWyVZgk/giphy.gif) ?

**Comment by dilyar85** [comment]
Hi @7fELF, thanks for your contribution and sorry for my delayed response.

I think the Travis CI build is failing because its go version is still on 1.11. Could you please update it to 1.13 (in `.travis.yml`) and the `README.md` file as well? The PR itself looks good to me, and I can approve & merge it once the CI is passed with the go version change. Thanks.

**Comment by 7fELF** [comment]
@dilyar85 Should be all good now, the Travis CI is passing :)

**Comment by dilyar85** [comment]
Awesome, and thanks for the quick fix!

**Review by dilyar85 — APPROVED** [review]

**Pull request merged**
